export ALLOW_MISSING_DEPENDENCIES=true
export LC_ALL="C"

export FOX_BUILD_DEVICE=judyln
export FOX_AB_DEVICE=1
export FOX_USE_NANO_EDITOR=1
export OF_FLASHLIGHT_ENABLE=0
export OF_SCREEN_H=2340
export OF_STATUS_H=94
export OF_STATUS_INDENT_LEFT=48
export OF_STATUS_INDENT_RIGHT=48
export OF_CLOCK_POS=1
export FOX_VANILLA_BUILD=1
export FOX_USE_TWRP_RECOVERY_IMAGE_BUILDER=1
export OF_USE_MAGISKBOOT=1
export OF_USE_MAGISKBOOT_FOR_ALL_PATCHES=1
export FOX_RESET_SETTINGS=0
